apiVersion: v1
kind: ConfigMap
metadata:
  name: render-config
  namespace: render-farm
data:
  TOTAL_FRAMES: "24"
  MAX_ITER: "300"
  FRAME_WIDTH: "640"
  FRAME_HEIGHT: "480"
  CENTER_X: "-0.743643887037151"
  CENTER_Y: "0.13182590420533"
