apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: render-output-pvc
  namespace: render-farm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
