apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: render-farm-ing
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: render-api-svc
                port:
                  number: {{ .Values.api.service.port }}
