apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: render-api-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: render-api-node-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: render-api-node-reader
  apiGroup: rbac.authorization.k8s.io
